from config import *

from PySide6.QtCore import (
    Qt,
    QPointF,
    QPoint,
    QEvent,
    QLine,
    QLineF,
    Signal,
)
from PySide6.QtGui import (
    QBrush,
    QPen,
    QMouseEvent,
    QKeyEvent,
    QResizeEvent,
    QPainter,
    QRgba64,
    QPixmap,
    QColor,
    QIcon,
    QWindow,
    QImage,
    QFont,
)
from PySide6.QtWidgets import (
    QApplication,
    QGraphicsItem,
    QGraphicsItemGroup,
    QGraphicsEllipseItem,
    QGraphicsRectItem,
    QGraphicsLineItem,
    QGraphicsTextItem,
    QGraphicsScene,
    QGraphicsView,
    QHBoxLayout,
    QStackedLayout,
    QPushButton,
    QSlider,
    QVBoxLayout,
    QWidget,
    QMainWindow,
    QLineEdit,
    QGraphicsSceneMouseEvent,
    QGraphicsPixmapItem,
    QSizePolicy,
    QLabel,
    QStackedWidget,
)